### ISSUE TITLE
Evaluating Scroll Position Too Early & Bind Once

### ISSUE THREAD

**Issue by AJeezy9** [gilbox/spark-scroll#10]
Two questions:

1.  I'm having a problem with certain Angular pages that have hero elements that are not fully loaded when the Spark Scroll script evaluates the scroll position, leaving elements directly below these hero elements to evaluate to already having passed the triggering scroll position. It corrects itself if I scroll up, but Is there any way to delay the scroll position evaluation or reset the scroll position to correct this problem?

2.  I'm using the latest stable version of AngularJS, but its unclear to me how to implement the bindOnce features using the new, native Angular directive.  I've tried placing the "::" in various places in the spark-scroll expression, but none of these places have worked.  Can you provide a quick example of how to do this?  

Thanks

**Comment by gilbox** [comment]
1. Not sure if this will work, but did you try `$broadcast`ing the `sparkInvalidate` event on `$rootScope` ?

2. How did you determine that one-time binding isn't working?

**Comment by gilbox** [comment]
closing this issue b/c no reply
