### ISSUE TITLE
How to reset the scroll downAddClass ? 

### ISSUE THREAD

**Issue by heldrida** [gilbox/spark-scroll#11]
Hi

This is not exactly an issue but I'm trying to reset spark-scroll, by removing the downAddClass  class name. How can I do that ? There's a requirement for this, where the content is not really destroyed but I'd like to have the scroll animations getting triggered once again if certain action happens!

**Comment by gilbox** [comment]
You can use `downRemoveClass` or `upRemoveClass` or create your own action handler.

**Comment by heldrida** [comment]
@gilbox thanks for looking! I know about the up|downRemoveClass, but is there a method to reset states whenever I want ? This two methods depend on the scroll position and for my current requirement I need to be able to reset the scroll states as I which.

**Comment by gilbox** [comment]
Hmm spark-scroll will only trigger an add/remove class action when it hits the scroll point that you set so spark-scroll won't stop you from just adding/removing the class yourself at any time. So you can just attach your own directive to the same element and have it manipulate the classes.

**Comment by heldrida** [comment]
Ok thanks!
