### ISSUE TITLE
from relative to fixed position

### ISSUE THREAD

**Issue by fxck** [gilbox/spark-scroll#15]
it's throwing errors when I try to get from relative to fixed position(`Cannot read property 'length' of null`) should I use `upRemoveClass` for this or something?

**Comment by fxck** [comment]
yeah, probably, looking at the demo...

Btw I really like the directive, haven't yet tested the performance, but other than that, really nice, better than skrollr which was my previous favorite.. if only it had a better documentation, wouldn't even know about `spark-id` if I didn't check the source..

**Comment by gilbox** [comment]
Thanks fxck. If you'd like to improve the documentation I'm happy to accept PRs.
