### ISSUE TITLE
can you fall back onto underscore?

### ISSUE THREAD

**Issue by episodeyang** [gilbox/spark-scroll#17]
Hi, 

Thanks for this great library! Our app currently uses underscore. Is it possible to use this without lo-dash and just use underscore?

Thanks!
Ge

**Comment by gilbox** [comment]
I'm pretty sure you can. What build system are you using? webpack, browserify, and requirejs all support aliasing pretty easily.

**Comment by gilbox** [comment]
closing b/c of inactivity
