### ISSUE TITLE
The trigger mechanism of spark-scroll-callback is broken

### ISSUE THREAD

**Issue by grapemix** [gilbox/spark-scroll#19]
Hi,

First, I want to thanks for your work. It is awesome. I am pretty excite about the spark-scroll-callback feature. However, it seems the trigger mechanism of spark-scroll-callback is broken. When I try the spark-trigger way, the trigger is not being used. When I try the spark-scroll way, it only fires the event based on the top of the page. I would expect the callback event will be fired after passing a spark-id, otherwise, the spark-scroll-callback feature will be useless. Would you mind take a look of the problem? Thanks.

**Comment by gilbox** [comment]
Hi @grapemix, 

I think you are running into issue #14 . I added a fix in the description of the issue. Please try out the fix and if it works, please submit a PR.

**Comment by grapemix** [comment]
Thanks for your quick reply. That's what I exactly need. It feels awesome when the lib author is so responsive and reliable ; )
